### ISSUE TITLE
Encoding pipes?

### ISSUE THREAD

**Issue by khromov** [mshick/add-pr-comment#104]
I have a workflow using this that prints a table which includes pipe characters. 

The workflow part is:

```yaml
- name: Comment PR
  uses: mshick/add-pr-comment@v2
  with:
    message-id: 'node-dependencies-count'
    message: |
      **👨‍💻 PR Branch Node Dependencies Count:**
      ```
      ${{ env.COUNT }}
      ```
    repo-token: '${{ github.token }}'
```

When I try to run this I get the error:

```
 Error: Unable to process file command 'env' successfully.
Error: Invalid format '| Package                          | Dependency Count |'
```

Is there some way to prevent this by correctly encoding the pipe signs?
