### ISSUE TITLE
Could ```message``` and ```message-path``` be combined

### ISSUE THREAD

**Issue by Betristor** [mshick/add-pr-comment#109]
I got a question about the composition of the message. Could we combine usage of message and message-path to form a new message. Like, a template is posed in message and then some dynamic message is posed in the file. By doing so, we could generate more complex message as comment.

**Comment by danielytics** [comment]
You can do this right now by using multiple steps, for example:
```
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            1. <<update1>>
            2. <<update2>>
      - uses: mshick/add-pr-comment@v2
        with:
          find: <<update1>>
          replace: Text Replacement 1
      - uses: mshick/add-pr-comment@v2
        with:
          find: <<update2>>
          replace: Text Replacement 2
```
results in the message:
> 1. Text Replacement 1
> 2. Text Replacement 2

As shown in https://github.com/mshick/add-pr-comment#find-and-replace you can also use `message-path` instead of `replace` for the replacement text, if you wish to take it from a file.
