### ISSUE TITLE
Force-fail the action

### ISSUE THREAD

**Issue by hussedev** [mshick/add-pr-comment#110]
Sometimes I wan't to leave a comment on a PR if an action fails, then I use it like this:
```
            - name: Step that fails
              id: failed_step
              continue-on-error: true
              run: |
                  echo "this fails" \
                  exit 1

            - name: Post Plan Failure
              if: steps.failed_step.outcome == 'failure'
              uses: mshick/add-pr-comment@v2
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  message: |
                       ```
                      ${{ steps.failed_step.outputs.stderr }}
                      ```
```
But then because the last action of the job was successful, the job status it's successful too.

It would be nice to have an argument 'force_fail' that if it's true... the action fails after putting the comment in the PR.

I already implemented it, but wasn't sure if I should make a PR or and Issue first.

This would be my first Open Source contribution!! ;P

**Comment by mshick** [comment]
In your example above, would this not work? In the example below I would expect the failure to carry forward, and any later actions that specifically only run on `failure` or `always` would still run. This would roughly accomplish what I think you're asking for.

```
- name: Step that fails
  id: failed_step
  run: |
      echo "this fails" \
      exit 1

- name: Post Plan Failure
  if: failure()
  uses: mshick/add-pr-comment@v2
  with:
      repo-token: ${{ secrets.GITHUB_TOKEN }}
      message: |
            ```
          ${{ steps.failed_step.outputs.stderr }}
          ```
```

I notice you're using `continue-on-error` above. That is specifically preventing setting the `failure()` status, which might be intentional, but in that case if this action were to force the failure you'd end up in the same place on all the later steps — you job would be in the `failure` state.

Also note the `message-failure` and similar props you can pass. If you wanted your message to always post _something_ then you could do something like this:

```
- name: Post Plan Failure
  if: always()
  uses: mshick/add-pr-comment@v2
  with:
      repo-token: ${{ secrets.GITHUB_TOKEN }}
      message: |
          No problems!
      message-failure: |
            ```
          ${{ steps.failed_step.outputs.stderr }}
          ```
```
