### ISSUE TITLE
Undesired performance with ```update-only``` setting at first run

### ISSUE THREAD

**Issue by Betristor** [mshick/add-pr-comment#111]
I had a workflow which will check a summary file after tests.
The logs are as follows:
```
Run mshick/add-pr-comment@v2
  with:
    update-only: true
    preformatted: true
    message-path: benchmark/summary.txt
......
  env:
    ARTIFACTS_PATH: ~/.julia/artifacts
    PACKAGES_PATH: ~/.julia/packages
    REGISTRIES_PATH: ~/.julia/registries
    PRECOMPILATION_CACHE_PATH: 
    JULIA_PKG_SERVER_REGISTRY_PREFERENCE: eager
no existing comment found and update-only is true, exiting
```
I desire that at the first run of this workflow, if the summary file exists, then a comment should be created to notify me and then in later runs, the comments should be updated if the condition still holds. But it seems that ```update-only``` setting could not statisfy both.
