### ISSUE TITLE
Is it possible to print an env value with multiple lines?

### ISSUE THREAD

**Issue by QuentinLuc** [mshick/add-pr-comment#23]
Here is my setup:
```
- name: Comment if PR
        uses: mshick/add-pr-comment@v1
        with:
          dummy-var: "hello world"
          message: |
            ## 🤖 Letsbuilders dependencies list 🤖
            Take a look at the Letsbuilders dependencies list bellow and make sure it is correct and does not contain multiple versions of the package or and also that each package is only listed once 🕵️
            ```
            "${{ env.LB_DEPS }}"
            ```

          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: true
```

`env.LB_DEPS` is basically the result of grep which is run in the previous step.  I'l like to display it in the comment but for some reason CRLF are not kept thus the result is displayed in one line.

Is there something I should be doing to fix that?

Thanks!

**Comment by mshick** [comment]
I don't really touch the message body so there shouldn't be an issue. It may have something to do with the github processing between steps.

Just a guess, perhaps you could try removing the `""` around the github expression... Maybe also experiment by setting an env var directly with line breaks, e.g., top level:

```yml
env:
  LB_DEPS: |
    foo
    bar
```

and see if that works. Will keep this open until we've figured out what is up!

**Comment by mshick** [comment]
@QuentinLuc I believe I found your answer here:

https://github.community/t/set-output-truncates-multiline-strings/16852/5

In short, you'll need to escape your newlines before echoing to the output. The Action interpolation will automatically un-escape them where you're printing them in the message.

Please let me know if that works for you.

**Comment by sulmanbashir** [comment]
Hello @mshick. A lot of thanks for this helpful tool ! However I'm facing a problem, maybe same like @QuentinLuc. My comment should return some environment variables. But I can't. Can someone explain me what I'm doing wrong ? Thanks.

<img width="807" alt="Capture d’écran 2020-09-11 à 17 15 02" src="https://user-images.githubusercontent.com/25442345/92942948-6cea2000-f452-11ea-811a-657903500fee.png">

**Comment by Guts** [comment]
FYI, same issue here. Using environment variable in the message arg make the action failing.

Tried:

```
Hello ${{ GITHUB_AUTHOR }}
hello '$GITHUB_AUTHOR'
```

both failing

**Comment by mshick** [comment]
@sulmanbashir Glad you figured it out! 

By way of explanation — the GitHub interpolation is only going to work for GitHub's context. e.g., `env.actor`. The `GITHUB_ACTOR` env variable, and all the other variables GitHub injects, are derived from the context and are present mostly as a convenience for scripts or actions.

@Guts `${{ env.GITHUB_AUTHOR }}` is not part of the GitHub context unless you assigned it somewhere. Here's a full list of [the default variables GitHub adds](https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables).

If you wanted to create an env variable you could interpolate you might do this:

```yaml
env:
  GITHUB_AUTHOR: ${{ github.actor }}

jobs:
  ...
  steps:
    action: mshick/add-pr-comment@v1
    with:
      message: |
        Hello ${{ env.GITHUB_AUTHOR }}
```

```
input -> github.actor = 'octocat'
output -> "Hello octocat"
```

Note that you have to assign the env variable somewhere higher up than the step itself for it to be available for interpolation in the message. Which is to say, an assignment on the step itself will *not* work as expected:

```yaml
env:
  SOME_VAR: foo

jobs:
  ...
  steps:
    action: mshick/add-pr-comment@v1
    env:
      GITHUB_AUTHOR: ${{ github.actor }}
    with:
      message: |
        Hello ${{ env.GITHUB_AUTHOR }}
```

```
input -> github.actor = 'octocat'
output -> "Hello "
```

Hope that helps!
