### ISSUE TITLE
[Question] How could one use string interpolation inside of the message?

### ISSUE THREAD

**Issue by stanislavromanov** [mshick/add-pr-comment#29]
Hello,

I would like to use string interpolation in the message and I'm trying but cannot figure it out. Is it even possible?

Here is my example:
```
    steps:
      - name: Set ticket number
        run: echo "TICKET_NUMBER=$(echo $GITHUB_REF_NAME_SLUG | cut -c1-9 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - uses: mshick/add-pr-comment@v1
        with:
          message: 'Link to JIRA ticket: https://jira.jira/jira/browse/$TICKET_NUMBER'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
```

The output is `Link to JIRA ticket: https://jira.jira/jira/browse/$TICKET_NUMBER`. If I do something like `'Link to JIRA ticket: https://jira.jira/jira/browse/${{ github.head_ref }}'` just to test it out the output is `https://jira.jira/jira/browse/`

**Comment by sigfrid** [comment]
Hi there,
Have you found a solution?

I need to add a comment with the outcome of the following expression 
`cat r56/coverage/.last_run.json | jq '.result.line'`.

I have tried a few interpolations but all without luck.

Thanks.

**Comment by mshick** [comment]
Apologies for not keeping up here. @stanislavromanov I believe your issue can be resolved by using the `set-output` syntax GitHub provides. See more here: https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter.

@sigfrid I believe this would also solve your issue.

So, something like this:

```yaml
    steps:
      - name: Set ticket number
        id: parse-ticket-number
        run: |
            TICKET_NUMBER=$(echo $GITHUB_REF_NAME_SLUG | cut -c1-9 | tr '[:upper:]' '[:lower:]')
            echo "::set-output name= TICKET_NUMBER::$TICKET_NUMBER"

      - uses: mshick/add-pr-comment@v1
        with:
          message: 'Link to JIRA ticket: https://jira.jira/jira/browse/${{ steps.parse-ticket-number.outputs.TICKET_NUMBER }}'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
```
