### ISSUE TITLE
Add env in message

### ISSUE THREAD

**Issue by eerison** [mshick/add-pr-comment#30]
Are there any why to  use `env` in comments like

```yaml
       -  name: Commenting environment link in PR
          uses: mshick/add-pr-comment@v1
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            message: |
              You can see your code in this [environment](https://mylink-$PR_NUMBER.herokuapp.com) 🚀
```
