### ISSUE TITLE
status: ${{ job.status }} is missing in the example in README.md

### ISSUE THREAD

**Issue by rene-hermenau** [mshick/add-pr-comment#72]
The doc in `main` is not updated and still shows the old example for status:

```
on:
  pull_request:

jobs:
  pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: mshick/add-pr-comment@v2
        with:
          if: always()
          message: |
            **Howdie!**
          message-failure: |
            Uh oh!
```
           
Eventhough you merged an updated example in https://github.com/mshick/add-pr-comment/pull/62/files

```
jobs:
  pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: mshick/add-pr-comment@v2
        with:
          if: always()
          message: |
            **Howdie!**
          message-failure: |
            Uh oh!
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
```

Not sure what went wrong.
