### ISSUE TITLE
Remove a previously added comment

### ISSUE THREAD

**Issue by jawotwi-heap** [mshick/add-pr-comment#74]
Can this remove a comment it's added on subsequent runs? Let me know if you need a use-case.

**Comment by v-dimitroff** [comment]
I came here searching for the same question - this would be extremely helpful to delete the previously set comment in the beginning of the workflow and restore/update the comment when the workflow completes successfully.

**Comment by mshick** [comment]
@jawotwi-heap A use-case would be helpful. There was a feature just merged which will "update" comments by deleting the old one and adding a new one. This helps keep the comments at the bottom of the issue. If your use-case is similar then perhaps the feature wouldn't be needed?

**Comment by andrey-hohlov** [comment]
@mshick `refresh-message-position` option looks promising, but it seems it doesn't work. I tried and it just edits the same comment.

```
on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add PR comment
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            🚀 This branch deployed at...
          refresh-message-position: true
```
