### ISSUE TITLE
Support multiple `message-paths` and concatenate them.

### ISSUE THREAD

**Issue by mshick** [mshick/add-pr-comment#90]

**Comment by kishaningithub** [comment]
Given https://github.com/mshick/add-pr-comment/issues/93 i feel there should be an option which creates multiple comments if `multiple-paths` are given. what do you think? That way there can probably be a step before calling this action which splits a very big comment into multiple comments and puts them in separate files.

**Comment by mshick** [comment]
@kishaningithub For #93 my preference would be to check the size of the message and break it into parts if we're going to hit the limit.

The use you describe above seems like it could be handled better by multiple instances of the action, for example:

```
on:
  pull_request:

jobs:
  pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: mshick/add-pr-comment@v2
        with:
          message-id: foo
          message-path: |
            foo/*.txt

      - uses: mshick/add-pr-comment@v2
        with:
          message-id: bar
          message-path: |
            bar/*.txt
```
