### ISSUE TITLE
error: body is too long (maximum is 65536 characters)

### ISSUE THREAD

**Issue by kishaningithub** [mshick/add-pr-comment#93]
## Problem

If pr comments are long, github API throws body is too long (maximum is 65536 characters) error

```
Error: Validation Failed: {"resource":"IssueComment","code":"unprocessable","field":"data","message":"Body is too long (maximum is 65536 characters)"}
```

Reproducible example file below, note that i am using the newly added `message-path` parameter to send the PR comment as a file.

```yml
name: PR comment test

on:
  push:
  workflow_call:

jobs:
  pr_comment_test:
    name: pr_command_help
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: comment message
        run: |
          wget --quiet https://github.com/kishaningithub/randomtext/releases/download/v1.2.1/randomtext_1.2.1_linux_amd64.deb
          sudo dpkg -i randomtext_1.2.1_linux_amd64.deb
          
          echo "Available commands (300 KB)" > pr-comment.txt
          randomtext -size 300KB -type words >> pr-comment.txt

          du -sh pr-comment.txt

      - name: Post apply output to GitHub PR
        uses: mshick/add-pr-comment@v2
        with:
          allow-repeats: true
          message-path: "pr-comment.txt"
```

Run Link: https://github.com/kishaningithub/github-actions-expermiments/actions/runs/4860867805/jobs/8665212807?pr=1

workflow file: https://github.com/kishaningithub/github-actions-expermiments/actions/runs/4860867805/workflow?pr=1

## Use case

- I am using this action to post output of terraform plan as a PR comment, this can get pretty long depending on the number of resources being affected
